// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgNFFmNIvDSj8jx5nx2AeOM-WY21En0U',
    appId: '1:760649996735:web:73a070b9582fa65db0e90a',
    messagingSenderId: '760649996735',
    projectId: 'smart-street-light-f6ee8',
    authDomain: 'smart-street-light-f6ee8.firebaseapp.com',
    storageBucket: 'smart-street-light-f6ee8.appspot.com',
    measurementId: 'G-27SVX4Q140',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxsvO--CnVdg--dI1DTCjNIi0yAeirUM',
    appId: '1:760649996735:android:0d24daf5ac93240cb0e90a',
    messagingSenderId: '760649996735',
    projectId: 'smart-street-light-f6ee8',
    storageBucket: 'smart-street-light-f6ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_omq51eDESQvuvkcetfPpel8oy_DSFt4',
    appId: '1:760649996735:ios:959355143fdbe7c5b0e90a',
    messagingSenderId: '760649996735',
    projectId: 'smart-street-light-f6ee8',
    storageBucket: 'smart-street-light-f6ee8.appspot.com',
    iosClientId:
        '760649996735-6uig1bvs92lvt6e7t7pjap8k9sbvanm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetLightManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_omq51eDESQvuvkcetfPpel8oy_DSFt4',
    appId: '1:760649996735:ios:959355143fdbe7c5b0e90a',
    messagingSenderId: '760649996735',
    projectId: 'smart-street-light-f6ee8',
    storageBucket: 'smart-street-light-f6ee8.appspot.com',
    iosClientId:
        '760649996735-6uig1bvs92lvt6e7t7pjap8k9sbvanm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetLightManagement',
  );
}
